// Code generated by MockGen. DO NOT EDIT.
// Source: proxy/istio.go

// Package proxy is a generated GoMock package.
package proxy

import (
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockIstioer is a mock of Istioer interface
type MockIstioer struct {
	ctrl     *gomock.Controller
	recorder *MockIstioerMockRecorder
}

// MockIstioerMockRecorder is the mock recorder for MockIstioer
type MockIstioerMockRecorder struct {
	mock *MockIstioer
}

// NewMockIstioer creates a new mock instance
func NewMockIstioer(ctrl *gomock.Controller) *MockIstioer {
	mock := &MockIstioer{ctrl: ctrl}
	mock.recorder = &MockIstioerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockIstioer) EXPECT() *MockIstioerMockRecorder {
	return m.recorder
}

// createVirtualService mocks base method
func (m *MockIstioer) createVirtualService(arg0 route) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "createVirtualService", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// createVirtualService indicates an expected call of createVirtualService
func (mr *MockIstioerMockRecorder) createVirtualService(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "createVirtualService", reflect.TypeOf((*MockIstioer)(nil).createVirtualService), arg0)
}

// listRegisteredRoutes mocks base method
func (m *MockIstioer) listRegisteredRoutes() (map[string]interface{}, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "listRegisteredRoutes")
	ret0, _ := ret[0].(map[string]interface{})
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// listRegisteredRoutes indicates an expected call of listRegisteredRoutes
func (mr *MockIstioerMockRecorder) listRegisteredRoutes() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "listRegisteredRoutes", reflect.TypeOf((*MockIstioer)(nil).listRegisteredRoutes))
}

// deleteRoute mocks base method
func (m *MockIstioer) deleteRoute(arg0 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "deleteRoute", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// deleteRoute indicates an expected call of deleteRoute
func (mr *MockIstioerMockRecorder) deleteRoute(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "deleteRoute", reflect.TypeOf((*MockIstioer)(nil).deleteRoute), arg0)
}
