name: build
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  golangci:
    name: golangci-lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.32
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.15
        uses: actions/setup-go@v2
        with:
          go-version: 1.15
        id: go

      - uses: actions/checkout@v2

      - name: Prepare env
        run: echo "GO_VERSION=$(go version | awk '{ print $3}' | sed 's/^go//')" >> $GITHUB_ENV

      - name: Test
        run: make test

      - name: Test coverage
        uses: codecov/codecov-action@v1

      - name: goreleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          args: release --snapshot --skip-publish --rm-dist
