name: Release
on:
  push:
    branches:
      - "!*"
    tags:
      - "v*.*.*"
jobs:
  build:
    runs-on: ubuntu-latest
    name: goreleaser
    steps:
      - name: Set up Go 1.15
        uses: actions/setup-go@v2
        with:
          go-version: 1.15
        id: go
      - uses: actions/checkout@v2
      - name: Prepare env
        run: echo "GO_VERSION=$(go version | awk '{ print $3}' | sed 's/^go//')" >> $GITHUB_ENV
      - name: Login to docker
        run: docker login -u harsimranmaan -p ${{ secrets.DOCKER_CD_TOKEN }}
      - name: Release via goreleaser
        uses: goreleaser/goreleaser-action@master
        with:
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
